CREATE TABLE public.verses (
    ID SERIAL PRIMARY KEY,
    LYRICS VARCHAR(500),
    AUTHOR VARCHAR(16)
);

CREATE TABLE public.guesses (
    LYRICS_ID INTEGER NOT NULL,
    GUESS VARCHAR(16),
    CONSTRAINT fk_lyrics_id FOREIGN KEY (LYRICS_ID) REFERENCES verses (ID) 
);